### Server
GET http://localhost:3000

##### USER #####
### Create User
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "Suwi Gautam",
    "email": "sth1@example.com",
    "password": "pw"
}

### Get All Users
GET http://localhost:3000/api/user

### Get a User
GET http://localhost:3000/api/user/1